# Generated by Django 6.0.7 on 2026-07-15 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('idade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade')),
                ('identidade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Identidade (RG)')),
                ('raca', models.CharField(blank=True, choices=[('BRANCA', 'Branca'), ('PRETA', 'Preta'), ('PARDA', 'Parda'), ('AMARELA', 'Amarela'), ('INDIGENA', 'Indígena')], max_length=20, null=True, verbose_name='Raça')),
                ('cor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor')),
                ('sexo', models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('NAO_BINARIO', 'Não-binário'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Sexo')),
                ('orientacao_sexual', models.CharField(blank=True, choices=[('HETEROSSEXUAL', 'Heterossexual'), ('HOMOSSEXUAL', 'Homossexual'), ('BISSEXUAL', 'Bissexual'), ('ASSEXUAL', 'Assexual'), ('OUTRO', 'Outro'), ('NAO_DECLARADA', 'Prefiro não declarar')], max_length=30, null=True, verbose_name='Orientação sexual')),
                ('genero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gênero')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('campus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campus')),
                ('curso', models.CharField(blank=True, max_length=200, null=True, verbose_name='Curso')),
                ('turno', models.CharField(blank=True, choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOTURNO', 'Noturno'), ('INTEGRAL', 'Integral')], max_length=20, null=True, verbose_name='Turno')),
                ('periodo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Período')),
                ('quantidade_disciplinas', models.PositiveIntegerField(default=0, verbose_name='Quantidade de disciplinas')),
                ('origem_escolar', models.CharField(blank=True, choices=[('PUBLICA', 'Escola Pública'), ('PRIVADA', 'Escola Privada')], max_length=20, null=True, verbose_name='Origem escolar')),
                ('eh_cotista', models.BooleanField(default=False, verbose_name='É cotista?')),
                ('moradia_estudantil', models.BooleanField(default=False, verbose_name='Usa moradia estudantil?')),
                ('email_institucional', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email institucional')),
                ('telefone_celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone celular')),
                ('tipo_conta', models.CharField(blank=True, choices=[('CORRENTE', 'Conta Corrente'), ('POUPANCA', 'Conta Poupança')], max_length=20, null=True, verbose_name='Tipo de conta')),
                ('numero_agencia', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número da agência')),
                ('numero_conta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da conta')),
                ('banco', models.CharField(blank=True, choices=[('001', 'Banco do Brasil'), ('104', 'Caixa Econômica Federal'), ('237', 'Bradesco'), ('341', 'Itaú'), ('033', 'Santander'), ('102', 'XP Investimentos'), ('OUTRO', 'Outro')], max_length=10, null=True, verbose_name='Banco')),
                ('banco_outro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especificar banco')),
                ('identidade_cpf_anexo', models.FileField(blank=True, null=True, upload_to='documents/identity/', verbose_name='CPF Anexo')),
                ('identidade_frente', models.FileField(blank=True, null=True, upload_to='documents/identity/', verbose_name='Identidade Frente')),
                ('identidade_verso', models.FileField(blank=True, null=True, upload_to='documents/identity/', verbose_name='Identidade Verso')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Estudante',
                'verbose_name_plural': 'Estudantes',
                'ordering': ['nome_completo'],
            },
        ),
    ]
