# Generated by Django 6.0.7 on 2026-07-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_pessoal',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email pessoal'),
        ),
    ]
