# Generated by Django 6.0.7 on 2026-07-11 14:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('idade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Idade')),
                ('identidade', models.CharField(blank=True, max_length=20, verbose_name='Identidade (RG)')),
                ('raca', models.CharField(blank=True, choices=[('BRANCA', 'Branca'), ('PRETA', 'Preta'), ('PARDA', 'Parda'), ('AMARELA', 'Amarela'), ('INDIGENA', 'Indígena')], max_length=20, verbose_name='Raça')),
                ('cor', models.CharField(blank=True, max_length=20, verbose_name='Cor')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=10, verbose_name='Sexo')),
                ('orientacao_sexual', models.CharField(blank=True, max_length=50, verbose_name='Orientação sexual')),
                ('genero', models.CharField(blank=True, max_length=50, verbose_name='Gênero')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('campus', models.CharField(max_length=100, verbose_name='Campus')),
                ('curso', models.CharField(max_length=200, verbose_name='Curso')),
                ('turno', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino'), ('NOTURNO', 'Noturno'), ('INTEGRAL', 'Integral')], max_length=20, verbose_name='Turno')),
                ('periodo', models.CharField(max_length=20, verbose_name='Período')),
                ('quantidade_disciplinas', models.IntegerField(default=0, verbose_name='Quantidade de disciplinas')),
                ('origem_escolar', models.CharField(blank=True, max_length=100, verbose_name='Origem escolar')),
                ('eh_cotista', models.BooleanField(default=False, verbose_name='É cotista')),
                ('moradia_estudantil', models.BooleanField(default=False, verbose_name='Moradia estudantil')),
                ('email_institucional', models.EmailField(max_length=254, verbose_name='Email institucional')),
                ('tipo_conta', models.CharField(blank=True, choices=[('CORRENTE', 'Corrente'), ('POUPANCA', 'Poupança')], max_length=20, verbose_name='Tipo de conta')),
                ('numero_agencia', models.CharField(blank=True, max_length=10, verbose_name='Número da agência')),
                ('numero_conta', models.CharField(blank=True, max_length=20, verbose_name='Número da conta')),
                ('banco', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('identidade_cpf_anexo', models.FileField(blank=True, null=True, upload_to='documentos/identidade_cpf/', verbose_name='CPF/RG anexo')),
                ('identidade_frente', models.FileField(blank=True, null=True, upload_to='documentos/identidade/frente/', verbose_name='Identidade frente')),
                ('identidade_verso', models.FileField(blank=True, null=True, upload_to='documentos/identidade/verso/', verbose_name='Identidade verso')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Estudante',
                'verbose_name_plural': 'Estudantes',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('ponto_referencia', models.TextField(blank=True, verbose_name='Ponto de referência')),
                ('horario_visita', models.CharField(blank=True, max_length=100, verbose_name='Horário de visita')),
                ('telefone_celular', models.CharField(max_length=15, verbose_name='Telefone celular')),
                ('procurar_por_pessoa', models.CharField(blank=True, max_length=200, verbose_name='Procurar por pessoa que more no endereço')),
                ('com_que_mora', models.CharField(blank=True, max_length=200, verbose_name='Com quem mora')),
                ('condicoes_moradia_familiar', models.TextField(blank=True, verbose_name='Condições de moradia familiar')),
                ('regiao_moradia', models.CharField(blank=True, choices=[('URBANA', 'Urbana'), ('RURAL', 'Rural'), ('PERIFERIA', 'Periferia'), ('CENTRO', 'Centro')], max_length=50, verbose_name='Região da moradia')),
                ('abastecimento_agua', models.CharField(blank=True, max_length=100, verbose_name='Abastecimento de água')),
                ('material_construcao', models.CharField(blank=True, max_length=100, verbose_name='Material de construção')),
                ('saneamento', models.CharField(blank=True, max_length=100, verbose_name='Saneamento')),
                ('contato_referencia_nome', models.CharField(blank=True, max_length=200, verbose_name='Contato de referência - Nome')),
                ('contato_referencia_telefone', models.CharField(blank=True, max_length=15, verbose_name='Contato de referência - Telefone')),
                ('mudou_endereco_para_estudar', models.BooleanField(default=False, verbose_name='Mudou do endereço para estudar no IFPE')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('estudante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='core.estudante', verbose_name='Estudante')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
