# Generated by Django 6.0.7 on 2026-07-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_pedagogo',
            field=models.BooleanField(default=False, verbose_name='É pedagogo'),
        ),
    ]
