# Generated by Django 6.0.7 on 2026-07-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_is_pedagogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_pedagogo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_assistente_social',
            field=models.BooleanField(default=False, verbose_name='É assistente social'),
        ),
    ]
