# Generated by Django 6.0.7 on 2026-07-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_estudante_matricula_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='matricula',
            field=models.CharField(max_length=50, unique=True, verbose_name='Matrícula'),
        ),
    ]
