# Generated by Django 6.0.7 on 2026-07-15 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Displacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mensal_transporte', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor mensal gasto com transporte (R$)')),
                ('trajeto_percorrido', models.TextField(help_text='Descreva o trajeto que você faz diariamente para chegar ao campus', verbose_name='Trajeto percorrido diariamente')),
                ('tipo_transporte', models.CharField(choices=[('ONIBUS', 'Ônibus'), ('METRO', 'Metrô'), ('CARRO', 'Carro próprio'), ('MOTO', 'Motocicleta'), ('BICICLETA', 'Bicicleta'), ('A_PE', 'A pé'), ('VAN', 'Van/Kombi'), ('OUTRO', 'Outro')], max_length=30, verbose_name='Tipo de transporte')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Deslocamento',
                'verbose_name_plural': 'Deslocamentos',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do edital')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de início')),
                ('data_fim', models.DateTimeField(verbose_name='Data de fim')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('CANCELADO', 'Cancelado')], default='FECHADO', max_length=20, verbose_name='Status')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Período de Inscrição',
                'verbose_name_plural': 'Períodos de Inscrição',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDA', 'Submetida'), ('EM_ANALISE', 'Em análise'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('indice_vulnerabilidade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Índice de vulnerabilidade estudantil')),
                ('foi_beneficiado_ultima_edicao', models.BooleanField(default=False, verbose_name='Foi beneficiado na última edição do programa?')),
                ('foi_beneficiado_beneficio_eventual', models.BooleanField(default=False, verbose_name='Foi beneficiado na última edição do benefício eventual?')),
                ('auxilio_digital', models.BooleanField(default=False, verbose_name='Solicita auxílio digital?')),
                ('recebe_bolsa_estudantil', models.BooleanField(default=False, verbose_name='Recebe algum tipo de bolsa estudantil?')),
                ('descricao_bolsa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição da bolsa')),
                ('beneficiario_social', models.BooleanField(default=False, verbose_name='É beneficiário de programa social ou possui inscrição no CadÚnico?')),
                ('cpf_familiar_beneficiario', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do familiar beneficiário do BPC/Bolsa Família')),
                ('valor_programa_social', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor recebido através do programa social (R$)')),
                ('comprovante_programa_social', models.FileField(blank=True, null=True, upload_to='documents/social/', verbose_name='Comprovante do programa social ou CADÚnico')),
                ('eh_chefe_familia', models.BooleanField(default=False, verbose_name='Você é chefe de família ou responsável pela própria subsistência?')),
                ('grau_parentesco_chefe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qual o grau de parentesco da pessoa que chefia a família?')),
                ('renda_bruta_familiar', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Renda bruta familiar (R$)')),
                ('renda_per_capita', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Renda per capita (R$)')),
                ('faixa_renda_per_capita', models.CharField(blank=True, choices=[('ATE_05_SALARIOS', 'Até 0,5 salário mínimo per capita'), ('ATE_1_SALARIO', 'Até 1 salário mínimo per capita'), ('ATE_15_SALARIOS', 'Até 1,5 salários mínimos per capita'), ('ACIMA_15_SALARIOS', 'Acima de 1,5 salários mínimos per capita')], max_length=30, null=True, verbose_name='Faixa de renda per capita')),
                ('renda_per_capita_extenso', models.CharField(blank=True, max_length=255, null=True, verbose_name='Renda per capita (por extenso)')),
                ('origem_renda_principal', models.CharField(blank=True, choices=[('TRABALHO', 'Trabalho formal/informal'), ('BENEFICIO_SOCIAL', 'Benefício social (BPC, Bolsa Família)'), ('PENSÃO', 'Pensão alimentícia'), ('APOSENTADORIA', 'Aposentadoria'), ('OUTROS', 'Outros')], max_length=30, null=True, verbose_name='Qual a origem da renda principal de sua família?')),
                ('alimentacao_escolar', models.BooleanField(default=False, verbose_name='Utiliza alimentação no ambiente escolar?')),
                ('xerox', models.BooleanField(default=False, verbose_name='Solicita auxílio para xerox?')),
                ('internet', models.BooleanField(default=False, verbose_name='Solicita auxílio para internet?')),
                ('acesso_saude', models.CharField(blank=True, choices=[('SUS', 'Sistema Único de Saúde (SUS)'), ('PLANODE_SAUDE', 'Plano de saúde privado'), ('PARTICULAR', 'Particular'), ('NAO_ACESSA', 'Não acessa serviços de saúde')], max_length=30, null=True, verbose_name='Como você acessa os serviços de saúde?')),
                ('acesso_educacao_fundamental', models.TextField(blank=True, null=True, verbose_name='Como você acessou à educação básica (Ensino Fundamental)?')),
                ('acesso_educacao_medio', models.TextField(blank=True, null=True, verbose_name='Como você acessa/acessou à educação básica (Ensino Médio)?')),
                ('frequentou_proifpe', models.BooleanField(default=False, verbose_name='Frequentou o PROIFPE (curso pré-vestibular do IFPE)?')),
                ('relato_vida', models.TextField(help_text='Conte um pouco sobre sua história e situação', verbose_name='Relato de vida')),
                ('condicoes_programa', models.TextField(blank=True, null=True, verbose_name='Condições do programa')),
                ('declaracao_veracidade', models.BooleanField(default=False, verbose_name='Declaro que todas as informações são verdadeiras')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de conclusão da inscrição')),
                ('documentacao_correta', models.BooleanField(default=False, verbose_name='Documentação correta?')),
                ('aluno_contemplado_bolsa', models.BooleanField(default=False, verbose_name='Aluno contemplado com bolsa?')),
                ('comentario_pedagogo', models.TextField(blank=True, null=True, verbose_name='Comentário do pedagogo')),
                ('valor_bolsa_permanencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da bolsa permanência (R$)')),
                ('data_analise', models.DateTimeField(blank=True, null=True, verbose_name='Data da análise')),
                ('pedagogo_responsavel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pedagogo responsável')),
                ('bens_moveis', models.TextField(blank=True, help_text='Liste os bens móveis da família', null=True, verbose_name='Bens Móveis')),
                ('bens_imoveis', models.TextField(blank=True, help_text='Liste os bens imóveis da família', null=True, verbose_name='Bens Imóveis')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment', to='family.address')),
                ('displacement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment', to='enrollments.displacement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
                ('enrollment_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='enrollments.enrollmentperiod')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-criado_em'],
                'unique_together': {('student', 'enrollment_period')},
            },
        ),
    ]
