# Generated by Django 6.0.7 on 2026-07-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='assistente_social_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assistente social responsável'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='classificacao',
            field=models.CharField(choices=[('ANALISE', 'Em Análise'), ('COM_PENDENCIA', 'Com Pendência'), ('NAO_REGULARIZADO', 'Não Regularizado'), ('REGULARIZADO', 'Regularizado'), ('NAO_ELEGIVEL', 'Não Elegível'), ('ELEGIVEL', 'Elegível'), ('CONTEMPLADO', 'Contemplado'), ('NAO_CONTEMPLADO', 'Não Contemplado')], default='ANALISE', help_text='Classificação da situação da inscrição pelo assistente social', max_length=30, verbose_name='Classificação'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='comentario_assistente_social',
            field=models.TextField(blank=True, help_text='Observações do assistente social sobre a classificação', null=True, verbose_name='Comentário do assistente social'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='data_classificacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da classificação'),
        ),
    ]
