# Generated by Django 6.0.7 on 2026-07-11 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('periodo_inscricao_abertura', models.DateTimeField(blank=True, null=True)),
                ('periodo_inscricao_fechamento', models.DateTimeField(blank=True, null=True)),
                ('periodo_avaliacao_abertura', models.DateTimeField(blank=True, null=True)),
                ('periodo_avaliacao_fechamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], default='ATIVO', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDA', 'Submetida'), ('EM_ANALISE', 'Em análise'), ('DEFERIDA', 'Deferida'), ('INDEFERIDA', 'Indeferida')], default='RASCUNHO', max_length=20)),
                ('classificacao', models.CharField(choices=[('ANALISE', 'Em Análise'), ('COM_PENDENCIA', 'Com Pendência'), ('NAO_REGULARIZADO', 'Não Regularizado'), ('REGULARIZADO', 'Regularizado'), ('NAO_ELEGIVEL', 'Não Elegível'), ('ELEGIVEL', 'Elegível'), ('CONTEMPLADO', 'Contemplado'), ('NAO_CONTEMPLADO', 'Não Contemplado')], default='ANALISE', max_length=30)),
                ('informacoes_estudante', models.JSONField(blank=True, default=dict)),
                ('informacoes_endereco', models.JSONField(blank=True, default=dict)),
                ('informacoes_familiares', models.JSONField(blank=True, default=list)),
                ('informacoes_deslocamento', models.JSONField(blank=True, default=dict)),
                ('informacoes_inscricao', models.JSONField(blank=True, default=dict)),
                ('documentos', models.JSONField(blank=True, default=list)),
                ('submetida_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='inscricoes.edital')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.estudante')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-criado_em'],
                'unique_together': {('edital', 'estudante')},
            },
        ),
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedagogo', models.CharField(max_length=255)),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('elegivel', models.BooleanField()),
                ('indice_vulnerabilidade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('deferida', models.BooleanField()),
                ('valor_bolsa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('criterios_avaliacao', models.JSONField(blank=True, default=dict)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analise', to='inscricoes.inscricao')),
            ],
            options={
                'verbose_name': 'Análise',
                'verbose_name_plural': 'Análises',
                'ordering': ['-data_analise'],
            },
        ),
        migrations.CreateModel(
            name='MembroFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField()),
                ('parentesco', models.CharField(max_length=50)),
                ('escolaridade', models.CharField(blank=True, max_length=100)),
                ('rendimento_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('possui_agravo_saude', models.BooleanField(default=False)),
                ('possui_necessidade_especifica', models.BooleanField(default=False)),
                ('vinculo_empregaticio', models.CharField(blank=True, max_length=100)),
                ('recebe_pensao', models.BooleanField(default=False)),
                ('imagem_cpf', models.FileField(blank=True, null=True, upload_to='familiares/cpf/')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='inscricoes.inscricao')),
            ],
            options={
                'verbose_name': 'Membro Familiar',
                'verbose_name_plural': 'Membros Familiares',
            },
        ),
    ]
