# Generated by Django 6.0.7 on 2026-08-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='campus',
            field=models.CharField(blank=True, help_text='Campus ao qual este edital está associado. Deixe em branco para todos os campi.', max_length=100, verbose_name='Campus'),
        ),
    ]
