# Generated by Django 6.0.7 on 2026-07-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='periodo_recurso_avaliacao_abertura',
            field=models.DateTimeField(blank=True, help_text='Período para avaliação dos recursos dos estudantes após resultado parcial', null=True, verbose_name='Período de avaliação dos recursos - Abertura'),
        ),
        migrations.AddField(
            model_name='edital',
            name='periodo_recurso_avaliacao_fechamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Período de avaliação dos recursos - Fechamento'),
        ),
        migrations.AddField(
            model_name='edital',
            name='periodo_recurso_estudante_submissao_abertura',
            field=models.DateTimeField(blank=True, help_text='Período para estudantes submeterem recursos após resultado parcial', null=True, verbose_name='Período de submissão de recursos pelos estudantes - Abertura'),
        ),
        migrations.AddField(
            model_name='edital',
            name='periodo_recurso_estudante_submissao_fechamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Período de submissão de recursos pelos estudantes - Fechamento'),
        ),
        migrations.AddField(
            model_name='edital',
            name='periodo_recurso_solicitacao_abertura',
            field=models.DateTimeField(blank=True, help_text='Período para o assistente social solicitar recursos', null=True, verbose_name='Período de solicitação de recursos - Abertura'),
        ),
        migrations.AddField(
            model_name='edital',
            name='periodo_recurso_solicitacao_fechamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Período de solicitação de recursos - Fechamento'),
        ),
        migrations.AddField(
            model_name='edital',
            name='periodo_resultado_final_divulgacao',
            field=models.DateTimeField(blank=True, help_text='Data de divulgação do resultado final', null=True, verbose_name='Período de divulgação do resultado final'),
        ),
        migrations.AddField(
            model_name='edital',
            name='periodo_resultado_parcial_divulgacao',
            field=models.DateTimeField(blank=True, help_text='Data de divulgação do resultado parcial para os estudantes', null=True, verbose_name='Período de divulgação do resultado parcial'),
        ),
    ]
