# Generated by Django 6.0.7 on 2026-07-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConectaGovMock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nome_cidadao', models.CharField(max_length=255)),
                ('nis', models.CharField(blank=True, max_length=20)),
                ('possui_cadastro_unico', models.BooleanField(default=False)),
                ('renda_per_capita', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('familiares', models.JSONField(blank=True, default=list)),
                ('beneficios_sociais', models.JSONField(blank=True, default=list)),
                ('data_consulta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ConectaGov Mock',
                'verbose_name_plural': 'ConectaGov Mocks',
            },
        ),
        migrations.CreateModel(
            name='QAcademicoMock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('nome_estudante', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=200)),
                ('campus', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=20)),
                ('turno', models.CharField(max_length=20)),
                ('status_matricula', models.CharField(max_length=20)),
                ('data_consulta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'QAcadêmico Mock',
                'verbose_name_plural': 'QAcadêmico Mocks',
            },
        ),
    ]
