# Generated by Django 6.0.7 on 2026-07-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('endereco_completo', models.TextField(blank=True, null=True, verbose_name='Endereço completo')),
                ('ponto_referencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ponto de referência')),
                ('horario_visita', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horário de visita')),
                ('telefone_celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone celular')),
                ('procurar_pessoa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Procurar por pessoa que more no endereço')),
                ('com_que_mora', models.CharField(blank=True, max_length=255, null=True, verbose_name='Com que você mora')),
                ('condicoes_moradia', models.CharField(blank=True, choices=[('PROPRIA', 'Própria'), ('ALUGADA', 'Alugada'), ('CEDIDA', 'Cedida'), ('OCUPACAO', 'Ocupação')], max_length=20, null=True, verbose_name='Condições de moradia familiar')),
                ('regiao_moradia', models.CharField(blank=True, choices=[('URBANA', 'Urbana'), ('RURAL', 'Rural')], max_length=20, null=True, verbose_name='Região da moradia')),
                ('abastecimento_agua', models.CharField(blank=True, choices=[('REDE_GERAL', 'Rede geral de distribuição'), ('POCO_ARTESIANO', 'Poço artesiano'), ('CACIMBA', 'Cacimba'), ('RIO_LAGOA', 'Rio ou lagoa'), ('OUTRO', 'Outro')], max_length=30, null=True, verbose_name='Abastecimento de água')),
                ('material_construcao', models.CharField(blank=True, choices=[('ALVENARIA', 'Alvenaria/tijolo'), ('MADEIRA', 'Madeira'), ('MISTA', 'Mista (alvenaria e madeira)'), ('TAIPA', 'Taipa'), ('OUTRO', 'Outro')], max_length=30, null=True, verbose_name='Material de construção')),
                ('saneamento', models.CharField(blank=True, choices=[('REDE_GERAL', 'Rede geral de esgoto'), ('FOSSA_SEPTICA', 'Fossa séptica'), ('FOSSA_RUDIMENTAR', 'Fossa rudimentar'), ('A_CEU_ABERTO', 'A céu aberto'), ('OUTRO', 'Outro')], max_length=30, null=True, verbose_name='Saneamento')),
                ('contato_referencia_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contato de referência - Nome')),
                ('contato_referencia_telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contato de referência - Telefone')),
                ('mudou_endereco_estudar', models.BooleanField(default=False, verbose_name='Mudou do endereço para estudar no IFPE?')),
                ('endereco_anterior', models.TextField(blank=True, null=True, verbose_name='Endereço anterior')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['cidade', 'bairro'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('inscricao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição')),
                ('grau_parentesco', models.CharField(choices=[('PAI', 'Pai'), ('MAE', 'Mãe'), ('IRMAO', 'Irmão(ã)'), ('AVO', 'Avô/Avó'), ('TIO', 'Tio(a)'), ('PRIMO', 'Primo(a)'), ('FILHO', 'Filho(a)'), ('CONJUGE', 'Cônjuge'), ('OUTRO', 'Outro')], max_length=30, verbose_name='Grau de parentesco')),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO_ESTAVEL', 'União estável')], max_length=20, null=True, verbose_name='Estado civil')),
                ('cpf_anexo', models.FileField(blank=True, null=True, upload_to='documents/family/', verbose_name='CPF Anexo')),
                ('escolaridade', models.CharField(blank=True, choices=[('ANALFABETO', 'Analfabeto'), ('FUNDAMENTAL_INCOMPLETO', 'Ensino Fundamental incompleto'), ('FUNDAMENTAL_COMPLETO', 'Ensino Fundamental completo'), ('MEDIO_INCOMPLETO', 'Ensino Médio incompleto'), ('MEDIO_COMPLETO', 'Ensino Médio completo'), ('SUPERIOR_INCOMPLETO', 'Ensino Superior incompleto'), ('SUPERIOR_COMPLETO', 'Ensino Superior completo'), ('POS_GRADUACAO', 'Pós-graduação')], max_length=40, null=True, verbose_name='Escolaridade')),
                ('possui_agravo_saude', models.BooleanField(default=False, verbose_name='Possui agravo de saúde?')),
                ('descricao_agravo', models.TextField(blank=True, null=True, verbose_name='Descrição do agravo')),
                ('possui_necessidade_especifica', models.BooleanField(default=False, verbose_name='Possui necessidade específica?')),
                ('descricao_necessidade', models.TextField(blank=True, null=True, verbose_name='Descrição da necessidade')),
                ('vinculo_empregaticio', models.CharField(blank=True, choices=[('CLT', 'CLT (Carteira assinada)'), ('AUTONOMO', 'Autônomo'), ('EMPRESARIO', 'Empresário'), ('DESEMPREGADO', 'Desempregado'), ('ESTUDANTE', 'Estudante'), ('APOSENTADO', 'Aposentado'), ('PENSIONISTA', 'Pensionista'), ('OUTRO', 'Outro')], max_length=30, null=True, verbose_name='Vínculo empregatício')),
                ('rendimento_mensal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Rendimento mensal (R$)')),
                ('recebe_pensao', models.BooleanField(default=False, verbose_name='Recebe pensão?')),
                ('valor_pensao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da pensão (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Membro Familiar',
                'verbose_name_plural': 'Membros Familiares',
                'ordering': ['nome'],
            },
        ),
    ]
