# Generated by Django 6.0.7 on 2026-07-30 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
        ('students', '0002_add_email_pessoal_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='students.student'),
        ),
    ]
