# Generated by Django 6.0.7 on 2026-07-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_add_student_to_familymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='address',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='address',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua'),
        ),
    ]
